name: Build and Deploy Edge

on:
  push:
    branches:
      - main

env:
  REGISTRY: 192.168.11.119:32000
  APP: hola-edge
  VERSION: ${{ github.run_number }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        run: |
          docker build -t $REGISTRY/$APP:$VERSION .

      - name: Push Image
        run: |
          docker push $REGISTRY/$APP:$VERSION

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EDGE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to K3s
        run: |
          ssh -o StrictHostKeyChecking=no fernando@192.168.11.119 \
          "sudo k3s kubectl set image deployment/$APP $APP=$REGISTRY/$APP:$VERSION"